version: '3'

services:
  adminer:
    container_name: adminer
    image: adminer:4.7.6
    ports:
      - 8080:8080
    links:
      - db:db
    environment:
      ADMINER_DEFAULT_SERVER: db
      ADMINER_PLUGINS: 'tables-filter sql-log'
    networks:
        - app-network
    restart: always
