version: '3'
services:
  #PHP Service
  app:
    container_name: app
    build:
      context: ./dockerfiles/php-fpm
      dockerfile: Dockerfile
      args:
        - PUID=${PHP_FPM_PUID}
        - PGID=${PHP_FPM_PGID}
    volumes:
      - ./:/var/www/html/:rw
      - ./dockerfiles/php-fpm/php${PHP_VERSION}.ini:/usr/local/etc/php/php.ini
    networks:
      - app-network
    restart: always
  db:
    image: mysql:5.7
    container_name: db
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "${DB_PORT}:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    networks:
      - app-network
    restart: always
  nginx:
    image: nginx:alpine
    container_name: nginx
    depends_on:
      - app
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html/:rw
      - ./dockerfiles/nginx/conf.d/:/etc/nginx/conf.d/
      - ./dockerfiles/nginx/logs/:/var/log/nginx/
    networks:
      - app-network
    restart: always

#Volumes
volumes:
  dbdata:
    driver: local

#Networks
networks:
  app-network:
    driver: bridge
